### ISSUE TITLE
Include d.ts

### ISSUE THREAD

**Issue by mizchi** [mizchi/TypedCoffeeScript#12]

**Comment by ggramlich** [comment]
Is this issue meant to support all the goodness from the https://github.com/borisyankov/DefinitelyTyped project?
Or is it about something different?

**Comment by mizchi** [comment]
Yes. I will use type-script definitions.
But I haven't research typescript intermediate expressions.

**Comment by mizchi** [comment]
mizchi/dts-parser https://github.com/mizchi/dts-parser

**Comment by mizchi** [comment]
https://github.com/mizchi/TypedCoffeeScript/issues/41
