### ISSUE TITLE
エラーメッセージにもっと情報を含めてほしい

### ISSUE THREAD

**Issue by pasberth** [mizchi/TypedCoffeeScript#15]
現在，このようなファイルを実行すると

```
$ cat examples/many.tcoffee
x :: String = 42
y :: String = 42
```

次のようなエラーが出ます

```
$ tcoffee examples/many.tcoffee
'x' is expected to String indeed Number
```

要望 1)

しかし静的な走査である以上次のように， x， y どちらもに言及して表示したほうが親切です

```
$ tcoffee examples/many.tcoffee
'x' is expected to String indeed Number
'y' is expected to String indeed Number
```

あるいは，欲を言えば，

要望 2)

```
$ tcoffee examples/many.tcoffee
examples/many.tcoffee:1:1: error: 'x' is expected to String indeed Number
x :: String = 42
^
examples/many.tcoffee:2:1: error: 'y' is expected to String indeed Number
y :: String = 42
^
```

このように表示してくれるととても嬉しいです

現在の実装から見て，最初の x, y に言及するだけでも大掛かりな
変更になることは間違いないと思います． (例外を使えないことになると思う)．
よろしければ対応してくださいませ．

**Comment by mizchi** [comment]
今のところASTを上から舐めて、壊れたところで例外を投げる、という実装になっています。
型検査を行った結果、すぐさま例外を履かずに例外(の予定)のキューに詰めて、その箇所については一応壊れたという情報だけを保持し、無視することで、例外の一覧を取得することは可能です。

基本的に型がないASTを対象にしているため、ここらへんは柔軟な対応が取ることは可能。v1.0を目安に対応を予定します。

**Comment by pasberth** [comment]
ありがとうです

**Comment by mizchi** [comment]
おわた
