### ISSUE TITLE
Class field types aren't enforced

### ISSUE THREAD

**Issue by qiemem** [mizchi/TypedCoffeeScript#34]
For example:

```
-------> class Point
........   x :: Int
........   y :: Int
........ 
[Function: Point]
tcoffee> p = new Point()
{}
tcoffee> p.x = 'hello'
'hello'
```

One problem is that the fields here are being added to the prototype. When `p.x = 'hello'` is run, it's creating a new, untyped field in the instance. 

However, it doesn't work for methods either:

```
-------> class Foo
........   sq :: (Int) -> Int
........   sq: (x) -> x*x
........ 
[Function: Foo]
tcoffee> foo = new Foo()
{}
tcoffee> foo.sq('hi')
NaN
```

You should be able to declare the types of fields in the constructor (this also doesn't work). Ideally, you should be able to do it either in the constructor body or in the arguments.

**Comment by mizchi** [comment]
Fixed
